'use strict';
(()=>{
 const el=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const desk=document.createElement('section');desk.id='reportDesk';desk.hidden=true;desk.setAttribute('aria-label','기업 보고서 작업 공간');
 desk.innerHTML='<header><strong id="deskCompany"></strong><span id="deskStatus" role="status"></span><button class="btn" id="deskSave">지금 저장</button><button class="btn" id="deskBackup">기업 전체 작업 다운로드</button><button class="btn" id="deskPreview">출력 미리보기</button><button class="btn" id="deskWord">Word 다운로드</button><button class="btn" id="deskPdf">PDF·인쇄</button><button class="btn" id="deskClose">목차별 작업 화면</button><button class="btn" id="deskHome">기업 목록</button></header><div class="desk-layout"><nav class="desk-nav" id="deskNav" aria-label="보고서 목차"></nav><div class="desk-scroll" id="deskScroll"><article class="report-paper" id="deskPaper"></article></div></div>';
 document.body.append(desk);
 const back=document.createElement('button');back.id='deskReturn';back.className='btn';back.textContent='← 보고서 작업 공간으로';document.querySelector('.writing-tabs').prepend(back);
 let returnChapter='',busy=false;
 const sourceFields=[['title','자료명'],['publisher','발행기관·작성자'],['date','발행일·기준기간'],['url','출처 URL'],['page','페이지·표 번호'],['kind','자료 성격'],['excerpt','근거 원문·수치'],['memo','해석·추가 확인']];
 function chapters(){return [...reportChapters.filter(c=>!['basic','defense'].includes(c.id)),...reportChapters.filter(c=>['basic','defense'].includes(c.id))];}
 function meta(){return companyProject.document.reportMeta??={title:companyProject.name+' 기업분석 보고서',asOf:'',masterPrompt:DEFAULT_REPORT_PROMPT,notes:''};}
 function touch(){markProjectDirty();rememberLocalDraft();}
 function section(id){const s=chapterData(id);s.sources??=[];s.attachments??=[];s.research??='';s.writingPrompt??='';return s;}
 const paragraphs=s=>(s.notes||'').split(/\n\s*\n/);
 const chartPos=(chart,count)=>chart.report?.position==='start'?0:Number.isInteger(chart.report?.position)?Math.max(0,Math.min(count,chart.report.position)):count;
 function button(text,fn,host){const b=document.createElement('button');b.className='btn';b.textContent=text;b.onclick=fn;host.append(b);return b;}
 function area(value,fn,host,label){const t=document.createElement('textarea');t.value=value||'';t.placeholder=label;t.setAttribute('aria-label',label);t.oninput=()=>{fn(t.value);t.style.height='auto';t.style.height=Math.max(100,t.scrollHeight)+'px';touch();};host.append(t);requestAnimationFrame(()=>{t.style.height=Math.max(100,t.scrollHeight)+'px';});return t;}
 function input(value,fn,host,label){const l=document.createElement('label');l.textContent=label;const i=document.createElement('input');i.type='text';i.value=value||'';i.oninput=()=>{fn(i.value);touch();};l.append(i);host.append(l);return i;}
 // Render a saved chart without opening it or touching the active chart, autosave or selection.
 function chartVisual(chart){const previous=state;try{state={...defaultState,...chart.state,...extras(chart.state)};const error=validateData(state.type,rows());if(error)throw Error(error);const plan=createPlan(),p=palettes[state.theme],f=plan.font;const root=document.createElementNS(NS,'svg');root.setAttribute('viewBox',`0 0 ${plan.width} ${plan.height}`);root.setAttribute('width',plan.width);root.setAttribute('height',plan.height);
  const addLocal=(tag,attrs,text,parent=root)=>{const n=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs||{})){if(k==='href'&&!String(v).startsWith('data:image/'))throw Error('제품 사진을 다시 첨부해주세요.');n.setAttribute(k,v);}if(text!=null)n.textContent=text;parent.append(n);return n;};
  addLocal('style',{},"text{font-family:'Noto Sans KR','Apple SD Gothic Neo',Arial,sans-serif}");addLocal('rect',{width:plan.width,height:plan.height,fill:'#fff'});
  const lines=(v,x,y,w,size,color,weight=400)=>pixelWrap(v,w,size).forEach((line,i)=>addLocal('text',{x,y:y+size+i*size*1.5,'font-size':size,fill:color,'font-weight':weight},line));
  addLocal('rect',{x:30,y:46,width:6,height:plan.titleHeight,fill:p.accent,rx:3});lines(state.title||'제목',50,40,plan.width-100,f*1.75,p.ink,800);if(state.subtitle)lines(state.subtitle,50,40+plan.titleHeight,plan.width-100,f,'#657187');addLocal('line',{x1:50,y1:plan.top-f*5,x2:plan.width-50,y2:plan.top-f*5,stroke:'#dce2ea'});const group=addLocal('g',{transform:`translate(0 ${plan.top})`});for(const c of plan.commands)addLocal(c.tag,c.attrs,c.text,group);lines('단위: '+(state.unit||'해당 없음'),50,plan.height-plan.footerHeight,plan.width-100,f*.85,'#657187');lines('자료: '+(state.source||'미기재'),50,plan.height-plan.footerHeight+f*1.7,plan.width-100,f*.85,'#657187');return {svg:new XMLSerializer().serializeToString(root),width:plan.width,height:plan.height};
 }finally{state=previous;}}
 function sourcesText(s){return s.sources.map((v,i)=>'['+(i+1)+'] '+sourceFields.filter(([k])=>v[k]).map(([k,label])=>label+': '+v[k]).join('\n')).join('\n\n');}
 async function navigate(id,chartId,add=false){try{await flushProject();returnChapter=id;desk.hidden=true;selectChapter(id);el('showVisuals').click();if(chartId)await openProjectChart(chartId);if(add)showChapterTemplates();}catch(e){toast(e.message);}}
 function resourcePanel(s,c,host){const d=document.createElement('details');d.className='desk-resources edit-only';const sum=document.createElement('summary');sum.textContent='출처·원문·조사 메모·첨부자료 ('+s.sources.length+'개 출처 / '+s.attachments.length+'개 파일)';d.append(sum);host.append(d);
  area(s.research,v=>s.research=v,d,'원문·조사 메모');area(s.questions,v=>s.questions=v,d,'추가 확인 사항');area(s.writingPrompt,v=>s.writingPrompt=v,d,'이 목차의 작성 요청문');
  button('자료를 포함한 작성 요청문 복사',()=>{selectChapter(c.id);reportWriting.refreshWriter();el('copySectionWritingPrompt').click();},d);
  const src=document.createElement('div');d.append(src);const drawSources=()=>{src.replaceChildren();for(const v of s.sources){const card=document.createElement('div');card.className='desk-source';src.append(card);for(const [key,label]of sourceFields){if(['excerpt','memo'].includes(key))area(v[key],x=>v[key]=x,card,label);else input(v[key],x=>v[key]=x,card,label);}button('이 출처 삭제',()=>{if(confirm('이 출처를 삭제할까요?')){s.sources=s.sources.filter(a=>a!==v);touch();drawSources();}},card);}};drawSources();button('＋ 출처 추가',()=>{s.sources.push({id:crypto.randomUUID()});touch();drawSources();},d);
  const upload=document.createElement('input');upload.type='file';upload.multiple=true;upload.setAttribute('aria-label',c.name+' 첨부자료 추가');d.append(upload);const files=document.createElement('div');d.append(files);
  const list=()=>{files.replaceChildren();for(const f of s.attachments){const row=document.createElement('div');row.className='desk-actions';const name=document.createElement('span');name.textContent=f.name;row.append(name);button('파일 받기',()=>{try{const bytes=Uint8Array.from(atob(f.data.split(',')[1]),ch=>ch.charCodeAt(0));download(new Blob([bytes],{type:'application/octet-stream'}),f.name);}catch{toast('첨부파일을 읽지 못했습니다.');}},row);button('삭제',()=>{if(confirm('이 파일을 보관함에서 삭제할까요?')){s.attachments=s.attachments.filter(a=>a!==f);touch();list();}},row);files.append(row);}};list();
  upload.onchange=async()=>{const project=companyProject;try{for(const f of Array.from(upload.files)){const data=await fileData(f);if(companyProject!==project)return;s.attachments.push({id:crypto.randomUUID(),name:f.name,size:f.size,type:f.type,data});touch();}list();await flushProject();}catch(e){toast(e.message);}finally{upload.value='';}};
 }
 function drawFigure(chart,c,s,count,host){const fig=document.createElement('figure');fig.className='desk-figure';fig.style.opacity=chart.report?.hidden?'.45':'1';const actions=document.createElement('div');actions.className='desk-actions edit-only';fig.append(actions);button('도식 수정',()=>navigate(c.id,chart.id),actions);const position=document.createElement('select');position.setAttribute('aria-label','도식 위치');for(let i=0;i<=count;i++){const o=document.createElement('option');o.value=i;o.textContent=i===0?'본문 앞':i+'번째 문단 뒤';position.append(o);}position.value=chartPos(chart,count);position.onchange=()=>{chart.report??={};chart.report.position=Number(position.value);touch();draw(c.id);};actions.append(position);
  const mode=document.createElement('select');mode.setAttribute('aria-label','도식 표시 방식');for(const [v,t]of [['diagram','원래 도식'],['table','편집 가능한 표']]){const o=document.createElement('option');o.value=v;o.textContent=t;mode.append(o);}mode.value=chart.report?.mode||'diagram';mode.onchange=()=>{chart.report??={};chart.report.mode=mode.value;touch();draw(c.id);};actions.append(mode);button(chart.report?.hidden?'보고서에 포함':'보고서에서 제외',()=>{chart.report??={};chart.report.hidden=!chart.report.hidden;touch();draw(c.id);},actions);
  const visual=document.createElement('div');visual.className='desk-visual';if(chart.report?.hidden)visual.dataset.excluded='true';try{if(chart.report?.mode==='table'){visual.innerHTML=reportTableExport.tableHtml(reportTableExport.currentTable(chart.state));const caption=document.createElement('figcaption');caption.textContent=chart.name+' · 단위: '+(chart.state.unit||'해당 없음')+' · 자료: '+(chart.state.source||'미기재');visual.prepend(caption);}else{const v=chartVisual(chart);const img=document.createElement('img');img.alt=chart.name;img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(v.svg);visual.append(img);}}catch(e){visual.className+=' desk-error';visual.textContent='도식 입력 확인 필요: '+e.message;}fig.append(visual);host.append(fig);
 }
 function draw(target){if(!companyProject)return;el('deskCompany').textContent=companyProject.name+' · 보고서 작업 공간';const paper=el('deskPaper'),nav=el('deskNav');paper.replaceChildren();nav.replaceChildren();const m=meta();const title=input(m.title,v=>{m.title=v;},paper,'보고서 제목');title.style.fontSize='26px';title.style.fontWeight='800';title.parentElement.className='edit-only';const h=document.createElement('h1');h.className='print-only';h.textContent=m.title;paper.append(h);const date=input(m.asOf,v=>m.asOf=v,paper,'분석 기준일');date.parentElement.className='edit-only';const dateP=document.createElement('p');dateP.className='print-only';dateP.textContent='분석 기준일: '+(m.asOf||'미입력');paper.append(dateP);
  const opt=document.createElement('label');opt.className='desk-toggle edit-only';const ck=document.createElement('input');ck.type='checkbox';ck.checked=m.exportResources==='yes';ck.onchange=()=>{m.exportResources=ck.checked?'yes':'no';touch();};opt.append(ck,document.createTextNode('출력에 조사 메모·출처·확인 사항 포함'));paper.append(opt);const common=document.createElement('details');common.className='desk-resources edit-only';common.innerHTML='<summary>기업 공통 프롬프트·조사 메모</summary>';area(m.masterPrompt??DEFAULT_REPORT_PROMPT,v=>m.masterPrompt=v,common,'보고서 공통 작성 프롬프트');area(m.notes,v=>m.notes=v,common,'기업 전체 조사 메모');paper.append(common);const note=document.createElement('p');note.className='desk-note edit-only';note.textContent='본문은 여기서 바로 작성합니다. 빈 줄로 문단을 나누면 도식을 문단 사이에 배치할 수 있습니다. 도식 수정 후 돌아오면 최신 모습으로 반영됩니다.';paper.append(note);
  for(const c of chapters()){if(c.id==='industry'){const h=document.createElement('h2');h.textContent='상세 목차';const p=document.createElement('p');p.textContent=chapters().filter(x=>!['executive','basic','defense'].includes(x.id)).map(x=>x.name).join('\n');paper.append(h,p);}const s=section(c.id);button(c.name,()=>el('desk-section-'+c.id).scrollIntoView({block:'start'}),nav);const block=document.createElement('section');block.className='desk-section';block.id='desk-section-'+c.id;const heading=document.createElement('h2');heading.textContent=c.name;block.append(heading);const controls=document.createElement('div');controls.className='desk-actions edit-only';button('＋ 도표·도식 추가',()=>navigate(c.id,null,true),controls);button('목차별 작업 화면',()=>navigate(c.id),controls);if(c.id==='executive')button('작성 형식 넣기',()=>{const outline='[핵심] 기업에 대한 종합 판단\n\n1. 기업 간단 설명\n주요 제품·고객·매출 구조·현재 상황\n\n2. 지분구조 및 지배구조\n최상위 주주·직접/간접 지분·주요 관계회사\n\n3. 투자 하이라이트와 성립 조건\n주요 근거·기대 효과·추가 확인 사항';if(s.notes.trim()&&!confirm('기존 본문 끝에 작성 형식을 추가할까요?'))return;s.notes=[s.notes,outline].filter(Boolean).join('\n\n');touch();draw(c.id);},controls);block.append(controls);
   const ps=paragraphs(s);button('＋ 문단 추가',()=>{s.notes+='\n\n';touch();draw(c.id);},controls);button('문단 배치 갱신',()=>draw(c.id),controls);for(let i=0;i<=ps.length;i++){for(const chart of s.charts.filter(a=>chartPos(a,ps.length)===i))drawFigure(chart,c,s,ps.length,block);if(i<ps.length){const edit=document.createElement('div');edit.className='edit-only';area(ps[i],v=>{ps[i]=v;s.notes=ps.join('\n\n');if(chapterId===c.id)el('chapterNotes').value=s.notes;},edit,c.name+' 본문 '+(i+1)+'번째 문단');block.append(edit);const p=document.createElement('p');p.className='print-only';p.textContent=ps[i];block.append(p);}}
   resourcePanel(s,c,block);paper.append(block);
  }if(target)requestAnimationFrame(()=>el('desk-section-'+target)?.scrollIntoView({block:'start'}));
 }
 async function open(target){if(!companyProject)return;if(captureProjectChart())touch();desk.hidden=false;desk.classList.remove('preview');el('deskPreview').textContent='출력 미리보기';draw(target);}
 async function save(){try{await flushProject();el('deskStatus').textContent='저장됨';return true;}catch(e){el('deskStatus').textContent=e.message;toast(e.message);return false;}}
 const priorStatus=projectStatus;projectStatus=function(text){priorStatus(text);el('deskStatus').textContent=text;};
 const companyBefore=openCompany;openCompany=async function(id){await companyBefore(id);if(companyProject?.id===id)open();};
 const listBefore=loadCompanyList;loadCompanyList=async function(){await listBefore();const cards=Array.from(el('companyCards').children);cards.forEach((card,i)=>{const item=companyList[i];if(!item)return;const wrap=document.createElement('div');wrap.className='company-card-wrap';card.replaceWith(wrap);wrap.append(card);const b=button('기업 삭제',async()=>{const answer=prompt('이 기업의 초안·출처·첨부파일·도식을 모두 삭제합니다. 먼저 필요한 작업을 다운로드해주세요. 삭제하려면 기업명 "'+item.name+'"을 입력하세요.');if(answer!==item.name){if(answer!==null)toast('기업명이 일치하지 않아 삭제하지 않았습니다.');return;}try{const p=await api('/api/projects/'+item.id);await api('/api/projects/'+item.id,{method:'DELETE',body:JSON.stringify({name:item.name,revision:p.revision})});localStorage.removeItem('reportProjectDraft:'+item.id);await loadCompanyList();toast('기업을 삭제했습니다.');}catch(e){toast(e.message);}},wrap);b.classList.add('company-delete');});};
 el('showWholeDraft').textContent='보고서 작업 공간';el('showWholeDraft').onclick=()=>open(chapterId);back.onclick=()=>open(returnChapter||chapterId);el('deskClose').onclick=async()=>{if(await save()){desk.hidden=true;reportWriting.refreshWriter();el('chapterNotes').value=chapterData().notes;el('chapterQuestions').value=chapterData().questions;}};el('deskHome').onclick=async()=>{if(await save()){await returnToCompanies();if(!companyProject)desk.hidden=true;}};el('deskSave').onclick=save;el('deskBackup').onclick=()=>el('backupProject').click();
 el('deskPreview').onclick=()=>{const next=!desk.classList.contains('preview');draw();desk.classList.toggle('preview',next);el('deskPreview').textContent=next?'작성으로 돌아가기':'출력 미리보기';if(next){for(const n of desk.querySelectorAll('[data-excluded]'))n.closest('figure').hidden=true;if(meta().exportResources==='yes')for(const c of chapters()){const s=section(c.id),b=el('desk-section-'+c.id);for(const [title,value]of [['조사 메모',s.research],['출처·근거',sourcesText(s)],['추가 확인 사항',s.questions]])if(value){const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=value;b.append(h,p);}}}};
 async function blocks(){const out=[{kind:'title',text:meta().title},{kind:'text',text:'분석 기준일: '+(meta().asOf||'미입력')}];for(const c of chapters()){if(c.id==='industry')out.push({kind:'heading',text:'상세 목차'},{kind:'text',text:chapters().filter(x=>!['executive','basic','defense'].includes(x.id)).map(x=>x.name).join('\n')});const s=section(c.id),ps=paragraphs(s);out.push({kind:'heading',text:c.name});for(let i=0;i<=ps.length;i++){for(const chart of s.charts.filter(a=>!a.report?.hidden&&chartPos(a,ps.length)===i)){if(chart.report?.mode==='table')out.push({kind:'table',data:reportTableExport.currentTable(chart.state),text:chart.name+' · 단위: '+(chart.state.unit||'해당 없음')+' · 자료: '+(chart.state.source||'미기재')});else out.push({kind:'image',...chartVisual(chart),text:chart.name});}if(i<ps.length&&ps[i])out.push({kind:'text',text:ps[i]});}if(meta().exportResources==='yes')for(const [title,text]of [['조사 메모',s.research],['출처·근거',sourcesText(s)],['추가 확인 사항',s.questions]])if(text)out.push({kind:'subheading',text:title},{kind:'text',text});}return out;}
 async function exporting(fn){if(busy)return;busy=true;const controls=Array.from(desk.querySelectorAll('header button'));controls.forEach(b=>b.disabled=true);desk.querySelector('.desk-layout').inert=true;el('deskStatus').textContent='보고서 파일을 준비하는 중…';try{if(!await save())return;await fn(await blocks());el('deskStatus').textContent='내보내기 준비 완료';}catch(e){el('deskStatus').textContent='내보내기 실패';toast('내보내기 실패: '+e.message);}finally{busy=false;controls.forEach(b=>b.disabled=false);desk.querySelector('.desk-layout').inert=false;}}
 el('deskWord').onclick=()=>exporting(async list=>download(await reportDocuments.word(list),companyProject.name+'_기업분석보고서.docx'));
 el('deskPdf').onclick=()=>exporting(async list=>reportDocuments.print(list));
 window.reportEditor={open,blocks,chartVisual,draw};loadCompanyList();
})();
