'use strict';
(()=>{
 const el=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const desk=document.createElement('section');desk.id='reportDesk';desk.hidden=true;desk.setAttribute('aria-label','보고서 초안 작업실');
 desk.innerHTML='<header><strong id="deskCompany"></strong><span id="deskStatus" role="status"></span><button class="btn" id="deskSave">지금 저장</button><button class="btn" id="deskBackup">기업 전체 작업 다운로드</button><button class="btn" id="deskPreview">출력 미리보기</button><button class="btn" id="deskWord">Word 다운로드</button><button class="btn" id="deskPdf">PDF·인쇄</button><button class="btn" id="deskClose">목차별 작업 화면</button><button class="btn" id="deskHome">기업 목록</button></header><div class="desk-layout"><nav class="desk-nav" id="deskNav" aria-label="보고서 목차"></nav><div class="desk-scroll" id="deskScroll"><article class="report-paper" id="deskPaper"></article></div></div>';
 document.body.append(desk);
 const back=document.createElement('button');back.id='deskReturn';back.className='btn';back.textContent='← 보고서 초안 작업실로 이동';document.querySelector('.topbar').prepend(back);
 let returnChapter='',busy=false,addIntent=null,returnParagraph='';
 const pm=window.reportParagraphModel;
 async function beginAdd(c,p){if(!await save())return;addIntent={company:companyProject.id,chapter:c.id,paragraph:p.id};selectChapter(c.id);showChapterTemplates();el('newChartTitle').textContent=c.name+' · 문단 '+(pm.ensure(section(c.id)).findIndex(a=>a.id===p.id)+1)+' · 도표·도식 선택';}
 el('newChartDialog').addEventListener('close',()=>{if(!desk.hidden)addIntent=null;});
 function acceptTemplate(){if(!addIntent||addIntent.company!==companyProject?.id||addIntent.chapter!==chapterId)return null;const id=addIntent.paragraph;returnChapter=addIntent.chapter;returnParagraph=id;addIntent=null;desk.hidden=true;return id;}
 const sourceFields=[['title','자료명'],['publisher','발행기관·작성자'],['date','발행일·기준기간'],['url','출처 URL'],['page','페이지·표 번호'],['kind','자료 성격'],['excerpt','근거 원문·수치'],['memo','해석·추가 확인']];
 const standardChapters=reportChapters.map(c=>({...c}));
 function outline(){return companyProject.document.reportOutline??=[...standardChapters.filter(c=>!['basic','defense'].includes(c.id)),...standardChapters.filter(c=>['basic','defense'].includes(c.id))].map(c=>({id:c.id,name:c.name}));}
 function addChapter(){const entry={id:'custom_'+crypto.randomUUID(),name:'새 목차'};outline().push(entry);chapters();touch();draw(entry.id);return entry;}
 function restoreDefaults(){const list=outline();for(const c of standardChapters)if(!list.some(v=>v.id===c.id))list.push({id:c.id,name:c.name});touch();draw();toast('빠진 기본 목차를 추가했습니다. 기존 제목과 내용은 유지됩니다.');}
 function chapters(){const entries=outline();for(let i=reportChapters.length-1;i>=0;i--)if(reportChapters[i].id.startsWith('custom_')&&!entries.some(e=>e.id===reportChapters[i].id))reportChapters.splice(i,1);return entries.map(entry=>{let base=reportChapters.find(c=>c.id===entry.id);if(!base){base={id:entry.id,name:entry.name,question:'이 목차에서 설명할 내용과 근거를 자유롭게 작성하세요.',choices:standardChapters.find(c=>c.id==='basic').choices};reportChapters.push(base);}base.name=entry.name;const original=standardChapters.find(c=>c.id===entry.id),settings=companyProject.document.sections[entry.id]||{},choices=settings.diagramTypes?.map(id=>templates.find(t=>t.id===id)).filter(Boolean);base.choices=choices?.length?choices.map(t=>({name:t.name,type:t.id,need:contracts[t.id].schema})):(original?.choices||standardChapters.find(c=>c.id==='basic').choices);base.question=settings.structureQuestion??original?.question??'이 목차에서 설명할 내용과 근거를 자유롭게 작성하세요.';return {...base,name:entry.name};});}
 const undoBar=document.createElement('div');undoBar.id='deletionUndo';undoBar.hidden=true;document.body.append(undoBar);let undoAction=null;
 function offerUndo(label,action){const company=companyProject.id;undoAction=()=>{if(companyProject?.id!==company)return;action();touch();if(!desk.hidden)draw();else selectChapter(chapterId);undoBar.hidden=true;undoAction=null;};undoBar.replaceChildren(document.createTextNode(label+' 삭제됨 '));button('삭제 취소',()=>undoAction?.(),undoBar);button('닫기',()=>{undoBar.hidden=true;},undoBar);undoBar.hidden=false;}
 function removeChart(id,chartId){const s=section(id),at=s.charts.findIndex(c=>c.id===chartId);if(at<0)return;const chart=s.charts.splice(at,1)[0];if(projectChartId===chartId)projectChartId=null;offerUndo('도식',()=>{s.charts.splice(Math.min(at,s.charts.length),0,chart);});touch();if(!desk.hidden)draw(id,chart.report?.paragraphId);else selectChapter(id);return save();}
 function removeParagraph(c,s,para){const at=s.paragraphs.indexOf(para),charts=s.charts.filter(a=>a.report.paragraphId===para.id);s.paragraphs.splice(at,1);s.charts=s.charts.filter(a=>a.report.paragraphId!==para.id);if(charts.some(a=>a.id===projectChartId))projectChartId=null;let placeholder=null;if(!s.paragraphs.length){placeholder={id:crypto.randomUUID(),text:''};s.paragraphs.push(placeholder);}pm.sync(s);offerUndo('문단과 소속 도식',()=>{if(placeholder&&!placeholder.text&&!s.charts.some(a=>a.report.paragraphId===placeholder.id))s.paragraphs=s.paragraphs.filter(p=>p!==placeholder);s.paragraphs.splice(Math.min(at,s.paragraphs.length),0,para);s.charts.push(...charts);pm.sync(s);});touch();draw(c.id);}
 function removeSection(c){const list=outline(),at=list.findIndex(a=>a.id===c.id),entry=list.splice(at,1)[0],data=companyProject.document.sections[c.id];delete companyProject.document.sections[c.id];if(chapterId===c.id){projectChartId=null;chapterId=list[0]?.id||'basic';}offerUndo('목차와 작성 내용',()=>{list.splice(Math.min(at,list.length),0,entry);companyProject.document.sections[c.id]=data;});touch();draw();}
 function meta(){return companyProject.document.reportMeta??={title:companyProject.name+' 기업분석 보고서',asOf:'',masterPrompt:DEFAULT_REPORT_PROMPT,notes:''};}
 function touch(){markProjectDirty();rememberLocalDraft();}
 function section(id){const s=chapterData(id);s.sources??=[];s.attachments??=[];s.research??='';s.writingPrompt??='';if(s.freeNotes==null)s.freeNotes=[s.research,sourcesText(s),s.questions,s.writingPrompt].filter(Boolean).join('\n\n');return s;}
 const paragraphs=s=>(s.notes||'').split(/\n\s*\n/);
 const chartPos=(chart,count)=>chart.report?.position==='start'?0:Number.isInteger(chart.report?.position)?Math.max(0,Math.min(count,chart.report.position)):count;
 function button(text,fn,host){const b=document.createElement('button');b.className='btn';b.textContent=text;b.onclick=fn;host.append(b);return b;}
 function area(value,fn,host,label){const t=document.createElement('textarea');t.value=value||'';t.placeholder=label;t.setAttribute('aria-label',label);t.oninput=()=>{fn(t.value);t.style.height='auto';t.style.height=Math.max(100,t.scrollHeight)+'px';touch();};host.append(t);requestAnimationFrame(()=>{t.style.height=Math.max(100,t.scrollHeight)+'px';});return t;}
 function input(value,fn,host,label){const l=document.createElement('label');l.textContent=label;const i=document.createElement('input');i.type='text';i.value=value||'';i.oninput=()=>{fn(i.value);touch();};l.append(i);host.append(l);return i;}
 // Render a saved chart without opening it or touching the active chart, autosave or selection.
 function chartVisual(chart){const previous=state;try{state={...defaultState,...chart.state,...extras(chart.state)};const error=validateData(state.type,rows());if(error)throw Error(error);const plan=createPlan(),p=palettes[state.theme],f=plan.font;const root=document.createElementNS(NS,'svg');root.setAttribute('viewBox',`0 0 ${plan.width} ${plan.height}`);root.setAttribute('width',plan.width);root.setAttribute('height',plan.height);
  const addLocal=(tag,attrs,text,parent=root)=>{const n=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs||{})){if(k==='href'&&!String(v).startsWith('data:image/'))throw Error('제품 사진을 다시 첨부해주세요.');n.setAttribute(k,v);}if(text!=null)n.textContent=text;parent.append(n);return n;};
  addLocal('style',{},"text{font-family:'Noto Sans KR','Apple SD Gothic Neo',Arial,sans-serif}");if(!state.transparent)addLocal('rect',{width:plan.width,height:plan.height,fill:'#fff'});
  const lines=(v,x,y,w,size,color,weight=400)=>pixelWrap(v,w,size).forEach((line,i)=>addLocal('text',{x,y:y+size+i*size*1.5,'font-size':size,fill:color,'font-weight':weight},line));
  addLocal('rect',{x:30,y:46,width:6,height:plan.titleHeight,fill:p.accent,rx:3});lines(state.title||'제목',50,40,plan.width-100,f*1.75,p.ink,800);if(state.subtitle)lines(state.subtitle,50,40+plan.titleHeight,plan.width-100,f,'#657187');addLocal('line',{x1:50,y1:plan.top-f*5,x2:plan.width-50,y2:plan.top-f*5,stroke:'#dce2ea'});const group=addLocal('g',{transform:`translate(0 ${plan.top})`});for(const c of plan.commands)addLocal(c.tag,c.attrs,c.text,group);lines('단위: '+(state.unit||'해당 없음'),50,plan.height-plan.footerHeight,plan.width-100,f*.85,'#657187');lines('자료: '+(state.source||'미기재'),50,plan.height-plan.footerHeight+f*1.7,plan.width-100,f*.85,'#657187');return {svg:new XMLSerializer().serializeToString(root),width:plan.width,height:plan.height,transparent:!!state.transparent,tableData:plan.tableData,cardData:plan.cardData,chartState:clone(state)};
 }finally{state=previous;}}
 function sourcesText(s){return s.sources.map((v,i)=>'['+(i+1)+'] '+sourceFields.filter(([k])=>v[k]).map(([k,label])=>label+': '+v[k]).join('\n')).join('\n\n');}
 async function navigate(id,chartId,add=false){try{const list=chapters();if(!list.some(c=>c.id===id))id=list[0]?.id;if(!id){toast('먼저 목차를 추가해주세요.');return;}await flushProject();returnChapter=id;desk.hidden=true;selectChapter(id);el('showVisuals').click();if(chartId)await openProjectChart(chartId);if(add)showChapterTemplates();}catch(e){toast(e.message);}}
 function resourcePanel(s,c,host){const d=document.createElement('details');d.className='desk-resources edit-only';const sum=document.createElement('summary');sum.textContent='자유 기록·첨부파일';d.append(sum);host.append(d);
  area(s.freeNotes,v=>s.freeNotes=v,d,'출처·원문·메모·요청문을 구분 없이 자유롭게 기록하세요.');
  button('이 목차의 초안·기록 복사',async()=>{try{await navigator.clipboard.writeText([c.name,s.notes,s.freeNotes].filter(Boolean).join('\n\n'));toast('초안과 기록을 복사했습니다.');}catch{toast('복사 권한을 확인해주세요.');}},d);
  const upload=document.createElement('input');upload.type='file';upload.multiple=true;upload.setAttribute('aria-label',c.name+' 첨부자료 추가');d.append(upload);const files=document.createElement('div');d.append(files);
  const list=()=>{files.replaceChildren();for(const f of s.attachments){const row=document.createElement('div');row.className='desk-actions';const name=document.createElement('span');name.textContent=f.name;row.append(name);button('파일 받기',()=>{try{const bytes=Uint8Array.from(atob(f.data.split(',')[1]),ch=>ch.charCodeAt(0));download(new Blob([bytes],{type:'application/octet-stream'}),f.name);}catch{toast('첨부파일을 읽지 못했습니다.');}},row);button('삭제',()=>{if(confirm('이 파일을 보관함에서 삭제할까요?')){s.attachments=s.attachments.filter(a=>a!==f);touch();list();}},row);files.append(row);}};list();
  upload.onchange=async()=>{const project=companyProject;try{for(const f of Array.from(upload.files)){const data=await fileData(f);if(companyProject!==project)return;s.attachments.push({id:crypto.randomUUID(),name:f.name,size:f.size,type:f.type,data});touch();}list();await flushProject();}catch(e){toast(e.message);}finally{upload.value='';}};
 }
 function drawFigure(chart,c,s,count,host){const fig=document.createElement('figure');fig.className='desk-figure';fig.dataset.chartId=chart.id;const actions=document.createElement('div');actions.className='desk-actions edit-only';fig.append(actions);button('복사',()=>window.workStudio?.copyChart(chart),actions);button('도식 수정',()=>{returnParagraph=chart.report.paragraphId;navigate(c.id,chart.id);},actions);button('도식 삭제',()=>removeChart(c.id,chart.id),actions);for(const [label,delta]of [['↑ 위로 이동',-1],['↓ 아래로 이동',1]]){const b=button(label,()=>{if(pm.moveChart(s,chart.id,delta)){touch();draw(c.id,chart.report.paragraphId);}},actions);const ps=pm.ensure(s),peers=s.charts.filter(a=>a.report.paragraphId===chart.report.paragraphId),i=peers.indexOf(chart),pi=ps.findIndex(p=>p.id===chart.report.paragraphId);b.disabled=delta<0?i===0&&pi===0:i===peers.length-1&&pi===ps.length-1;}
  const mode=document.createElement('select');mode.setAttribute('aria-label','도식 표시 방식');for(const [v,t]of [['diagram','원래 도식'],['table','편집 가능한 표']]){const o=document.createElement('option');o.value=v;o.textContent=t;mode.append(o);}mode.value=chart.report?.mode||'diagram';mode.onchange=()=>{chart.report??={};chart.report.mode=mode.value;touch();draw(c.id);};actions.append(mode);
  const visual=document.createElement('div');visual.className='desk-visual';try{if(chart.report?.mode==='table'){visual.innerHTML=reportTableExport.tableHtml(reportTableExport.currentTable(chart.state));const caption=document.createElement('figcaption');caption.textContent=chart.name+' · 단위: '+(chart.state.unit||'해당 없음')+' · 자료: '+(chart.state.source||'미기재');visual.prepend(caption);visual.addEventListener('dblclick',event=>{if(event.target.tagName!=='TD')return;studioRefinements.editText(chart,event.target.textContent.trim(),candidate=>{chart.state=candidate;if(projectChartId===chart.id){state=clone(candidate);syncControls();render();}touch();draw(c.id);});});}else{const v=chartVisual(chart);const node=new DOMParser().parseFromString(v.svg,'image/svg+xml').documentElement;node.setAttribute('aria-label',chart.name);node.addEventListener('dblclick',event=>{if(event.target.tagName.toLowerCase()!=='text')return;studioRefinements.editText(chart,event.target.textContent.trim(),candidate=>{chart.state=candidate;if(projectChartId===chart.id){state=clone(candidate);syncControls();render();}touch();draw(c.id);});});visual.append(document.importNode(node,true));visual.firstElementChild.addEventListener('dblclick',event=>{if(event.target.tagName.toLowerCase()!=='text')return;studioRefinements.editText(chart,event.target.textContent.trim(),candidate=>{chart.state=candidate;if(projectChartId===chart.id){state=clone(candidate);syncControls();render();}touch();draw(c.id);});});}}catch(e){visual.className+=' desk-error';visual.textContent='도식 입력 확인 필요: '+e.message;}fig.append(visual);host.append(fig);
 }
 function draw(target,paragraphTarget){if(!companyProject)return;el('deskCompany').textContent='보고서 초안 작업실';const paper=el('deskPaper'),nav=el('deskNav');paper.replaceChildren();nav.replaceChildren();button('＋ 기본 목차 가져오기',restoreDefaults,nav);const m=meta();const title=input(m.title,v=>{m.title=v;},paper,'보고서 제목');title.style.fontSize='26px';title.style.fontWeight='800';title.parentElement.className='edit-only';const h=document.createElement('h1');h.className='print-only';h.textContent=m.title;paper.append(h);const date=input(m.asOf,v=>m.asOf=v,paper,'분석 기준일');date.parentElement.className='edit-only';const dateP=document.createElement('p');dateP.className='print-only';dateP.textContent='분석 기준일: '+(m.asOf||'미입력');paper.append(dateP);
  const common=document.createElement('details');common.className='desk-resources edit-only';common.innerHTML='<summary>기업 공통 프롬프트·조사 메모</summary>';area(m.masterPrompt??DEFAULT_REPORT_PROMPT,v=>m.masterPrompt=v,common,'보고서 공통 작성 프롬프트');area(m.notes,v=>m.notes=v,common,'기업 전체 조사 메모');paper.append(common);const note=document.createElement('p');note.className='desk-note edit-only';note.textContent='목차 제목을 클릭해 수정하고 목차·문단·도식은 위아래 버튼으로 옮기세요. 본문·출처·원문은 구분 없이 자유롭게 작성할 수 있습니다. 문단마다 본문과 이를 설명하는 도식을 함께 관리합니다. 문단의 위아래 이동은 소속 도식도 함께 옮깁니다. 도식은 위아래 버튼으로 순서를 바꾸며, 경계에서는 이웃 문단으로 이동합니다.';paper.append(note);
  for(const c of chapters()){const s=section(c.id);button(c.name,()=>el('desk-section-'+c.id).scrollIntoView({block:'start'}),nav).dataset.chapter=c.id;const block=document.createElement('section');block.className='desk-section';block.id='desk-section-'+c.id;const heading=document.createElement('h2');heading.textContent=c.name;heading.contentEditable='plaintext-only';heading.setAttribute('aria-label','목차 제목 수정');heading.title='클릭하여 목차 이름 수정';heading.setAttribute('role','textbox');heading.setAttribute('tabindex','0');heading.oninput=()=>{const entry=outline().find(a=>a.id===c.id);entry.name=heading.textContent;c.name=entry.name;const registered=reportChapters.find(v=>v.id===c.id);if(registered)registered.name=entry.name;touch();const navButton=nav.querySelector('[data-chapter=\"'+c.id+'\"]');if(navButton)navButton.textContent=entry.name;};block.append(heading);const controls=document.createElement('div');controls.className='desk-actions edit-only';for(const [label,delta]of [['↑ 위로 이동',-1],['↓ 아래로 이동',1]]){const list=outline(),at=list.findIndex(a=>a.id===c.id),btn=button(label,()=>{const to=at+delta;if(to<0||to>=list.length)return;[list[at],list[to]]=[list[to],list[at]];touch();draw(c.id);},controls);btn.disabled=at+delta<0||at+delta>=list.length;}button('목차 삭제',()=>removeSection(c),controls);if(c.id==='executive')button('작성 형식 넣기',()=>{const outline='[핵심] 기업에 대한 종합 판단\n\n1. 기업 간단 설명\n주요 제품·고객·매출 구조·현재 상황\n\n2. 지분구조 및 지배구조\n최상위 주주·직접/간접 지분·주요 관계회사\n\n3. 투자 하이라이트와 성립 조건\n주요 근거·기대 효과·추가 확인 사항';if(s.notes.trim()&&!confirm('기존 본문 끝에 작성 형식을 추가할까요?'))return;s.notes=[s.notes,outline].filter(Boolean).join('\n\n');touch();draw(c.id);},controls);block.append(controls);
   const ps=pm.ensure(s);button('＋ 문단 추가',()=>{s.paragraphs.push({id:crypto.randomUUID(),text:''});pm.sync(s);touch();draw(c.id,s.paragraphs.at(-1).id);},controls);for(let i=0;i<ps.length;i++){const para=ps[i],group=document.createElement('section');group.className='desk-paragraph';group.id='paragraph-'+para.id;group.dataset.paragraphId=para.id;const bar=document.createElement('div');bar.className='desk-actions paragraph-tools edit-only';const label=document.createElement('strong');label.textContent='문단 '+(i+1);bar.append(label);button('＋ 이 문단에 도표·도식 추가',()=>beginAdd(c,para),bar);for(const [name,delta]of [['↑ 위로 이동',-1],['↓ 아래로 이동',1]]){const b=button(name,()=>{if(pm.moveParagraph(s,para.id,delta)){touch();draw(c.id,para.id);}},bar);b.disabled=i+delta<0||i+delta>=ps.length;}button('문단 삭제',()=>removeParagraph(c,s,para),bar);group.append(bar);const edit=document.createElement('div');edit.className='edit-only';area(para.text,v=>{para.text=v;pm.sync(s);if(chapterId===c.id)el('chapterNotes').value=s.notes;},edit,para.hint||c.name+' 문단 '+(i+1)+' 본문');group.append(edit);const p=document.createElement('p');p.className='print-only';p.textContent=para.text;group.append(p);for(const chart of s.charts.filter(a=>a.report.paragraphId===para.id))drawFigure(chart,c,s,ps.length,group);block.append(group);}
   resourcePanel(s,c,block);paper.append(block);
  }const addSection=document.createElement('div');addSection.className='desk-actions edit-only';button('＋ 새 목차 추가',addChapter,addSection);paper.append(addSection);drawChapterNav();if(target)requestAnimationFrame(()=>(paragraphTarget?el('paragraph-'+paragraphTarget):el('desk-section-'+target))?.scrollIntoView({block:'start'}));
 }
 async function open(target){if(!companyProject)return;if(captureProjectChart())touch();desk.hidden=false;desk.classList.remove('preview');el('deskPreview').textContent='출력 미리보기';draw(target,returnParagraph);}
 async function save(){try{await flushProject();el('deskStatus').textContent='저장됨';return true;}catch(e){el('deskStatus').textContent=e.message;toast(e.message);return false;}}
 const priorStatus=projectStatus;projectStatus=function(text){priorStatus(text);el('deskStatus').textContent=text;};
 const companyBefore=openCompany;openCompany=async function(id){undoBar.hidden=true;undoAction=null;await companyBefore(id);if(companyProject?.id===id)open();};
 const listBefore=loadCompanyList;loadCompanyList=async function(){await listBefore();const cards=Array.from(el('companyCards').children);cards.forEach((card,i)=>{const item=companyList[i];if(!item)return;const wrap=document.createElement('div');wrap.className='company-card-wrap';card.replaceWith(wrap);wrap.append(card);const b=button('기업 삭제',async()=>{const answer=prompt('이 기업의 초안·출처·첨부파일·도식을 모두 삭제합니다. 먼저 필요한 작업을 다운로드해주세요. 삭제하려면 기업명 "'+item.name+'"을 입력하세요.');if(answer!==item.name){if(answer!==null)toast('기업명이 일치하지 않아 삭제하지 않았습니다.');return;}try{const p=await api('/api/projects/'+item.id);await api('/api/projects/'+item.id,{method:'DELETE',body:JSON.stringify({name:item.name,revision:p.revision})});localStorage.removeItem('reportProjectDraft:'+item.id);await loadCompanyList();toast('기업을 삭제했습니다.');}catch(e){toast(e.message);}},wrap);b.classList.add('company-delete');});};
 el('showWholeDraft').textContent='보고서 초안 작업실';el('showWholeDraft').onclick=()=>open(chapterId);back.onclick=()=>open(returnChapter||chapterId);const studioButton=document.createElement('button');studioButton.id='deskStudio';studioButton.className='btn';studioButton.textContent='← 도식/도표 작업실로 이동';desk.querySelector('header').prepend(studioButton);studioButton.onclick=()=>navigate(chapterId);el('deskClose').hidden=true;el('deskHome').onclick=async()=>{if(await save()){await returnToCompanies();if(!companyProject)desk.hidden=true;}};el('deskSave').onclick=save;el('deskBackup').onclick=()=>el('backupProject').click();
 el('deskPreview').onclick=()=>{const next=!desk.classList.contains('preview');draw();desk.classList.toggle('preview',next);el('deskPreview').textContent=next?'작성으로 돌아가기':'출력 미리보기';if(next)for(const c of chapters()){const s=section(c.id);if(s.freeNotes){const p=document.createElement('p');p.textContent=s.freeNotes;el('desk-section-'+c.id).append(p);}}};
 async function blocks(){const out=[{kind:'title',text:meta().title},{kind:'text',text:'분석 기준일: '+(meta().asOf||'미입력')}];for(const c of chapters()){const s=section(c.id),ps=paragraphs(s);out.push({kind:'heading',text:c.name});for(const para of pm.ensure(s)){if(para.text)out.push({kind:'text',text:para.text});for(const chart of s.charts.filter(a=>a.report.paragraphId===para.id)){if(chart.report?.mode==='table')out.push({kind:'table',data:reportTableExport.currentTable(chart.state),text:chart.name+' · 단위: '+(chart.state.unit||'해당 없음')+' · 자료: '+(chart.state.source||'미기재')});else out.push({kind:'image',...chartVisual(chart),text:chart.name});}}if(s.freeNotes)out.push({kind:'text',text:s.freeNotes});}return out;}
 async function exporting(fn){if(busy)return;busy=true;const controls=Array.from(desk.querySelectorAll('header button'));controls.forEach(b=>b.disabled=true);desk.querySelector('.desk-layout').inert=true;el('deskStatus').textContent='보고서 파일을 준비하는 중…';try{if(!await save())return;await fn(await blocks());el('deskStatus').textContent='내보내기 준비 완료';}catch(e){el('deskStatus').textContent='내보내기 실패';toast('내보내기 실패: '+e.message);}finally{busy=false;controls.forEach(b=>b.disabled=false);desk.querySelector('.desk-layout').inert=false;}}
 el('deskWord').onclick=()=>exporting(async list=>download(await reportDocuments.word(list),companyProject.name+'_기업분석보고서.docx'));
 el('deskPdf').onclick=()=>exporting(async list=>reportDocuments.print(list));
 const deskActions=document.createElement('div');deskActions.className='desk-header-actions';const release=document.createElement('small');release.className='app-release';release.textContent='버전 2026.09.17-08';deskActions.append(release);for(const child of Array.from(desk.querySelector('header').children))if(!['deskStudio','deskCompany'].includes(child.id))deskActions.append(child);desk.querySelector('header').append(deskActions);
 window.reportEditor={open,blocks,chartVisual,draw,acceptTemplate,removeChart,addChapter,restoreDefaults};loadCompanyList();
})();
